---
# yaml document begin with document seprator
  - #this minus indicate list of item in python
    #the target where your play will run
    hosts: db1
    vars:
      web_pkg: httpd
      firewall_okg: firewalld
      pearl_pkg: perl
      rule: http
    tasks:
      - name: install packages
        yum: 
          name:
            - "{{ web_pkg }}"
            - "{{ firewall_okg }}"
            - "{{ pearl_pkg }}"
          state: absent
      - name: open the port for rule
        firewalld:
          service: "{{ rule }}"
          permanent: true
          immediate: true
          state: disabled
